spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/sgh?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Chongqing
    driver-class-name:
  thymeleaf:
    cache: false

server:
  port: 5555
